### ISSUE TITLE
Failed to Install: "result.Executable().One undefined"

### ISSUE THREAD

**Issue by takuchalle** [b4b4r07/gist#1]
Hi

When I install b4b4r07/gist, an error is occurred as below.
```
$ go get github.com/b4b4r07/gist 
# github.com/b4b4r07/gist/util
../../go/src/github.com/b4b4r07/gist/util/util.go:103: result.Executable().One undefined (type *colon.Results has no field or method One)
```

I think Results.One function was removed from b4b4r07/go-colon repository [two days ago](https://github.com/b4b4r07/go-colon/commit/4b5f320da251a0e9cf73c8e7636ca6d16f9c3f3b).
Could you check it? I hope I didn't miss my operation.

**Comment by babarot** [comment]
Thanks to reporting, fixed
