### ISSUE TITLE
`gist new` returns 404 error if GitHub token has no OAuth access to gists

### ISSUE THREAD

**Issue by yumitsu** [b4b4r07/gist#7]
It's not even a real bug, but maybe error message should be a little bit more accurate (at least not 404):
```
[ERROR]: POST https://api.github.com/gists: 404 Not Found []
```

**Comment by babarot** [comment]
This cannot be reproduced. In my local, gist returned 401. This is expected behavior.

```console
$ gist new
GITHUB_TOKEN: ****█
[ERROR]: GET https://api.github.com/users/b4b4r07/gists?per_page=100: 401 Bad credentials []
[1]    81853 exit 1     gist new
```

If the report which happened in yours is correct (and it’s bug) could you give me more details?

**Comment by yumitsu** [comment]
@b4b4r07 Here is terminal record - https://terminalizer.com/view/d02f22123091
Everything I needed to reproduce it is to uncheck this checkbox for `gist` oauth scope:
![Screen Shot 2020-02-12 at 00 30 52](https://user-images.githubusercontent.com/108335/74281738-05d78200-4d30-11ea-89aa-53b860d335ce.png)

**Comment by babarot** [comment]
it's now stale a bit, so closing issue. if you have still any problems please let me know
